# Step 1: Build the user's application
FROM kabanero/ubi8-maven:0.3.1 as compile

RUN  groupadd java_group \
   && useradd --gid java_group --shell /bin/bash --create-home java_user \
   && mkdir -p /mvn/repository \
   && chown -R java_user:java_group /mvn \
   && mkdir -p /data/config/resources \
   && chown -R java_user:java_group /data/config \
# make a well known place for shared library jars seperate from the rest of the defaultServer contents (to help with caching)
   && mkdir /data/configlibdir \
   && chown -R java_user:java_group /data/configlibdir \
   &&  mkdir /data/shared \
   && chown -R java_user:java_group /data/shared 

#USER java_user
USER root

# Copy and build the dev.appsody:java-openliberty parent pom
COPY --chown=java_user:java_group ./pom.xml /project/pom.xml
RUN cd /project && mvn -B install dependency:go-offline -DskipTests

# Prime image
#   a) Prime .m2/repository with common artifacts 
#   b) Create target/liberty/wlp/usr/servers/defaultServer dir
COPY --chown=java_user:java_group ./preload-m2-pom.xml /project/user-app/preload-m2-pom.xml
RUN cd /project/user-app && \ 
    mvn -B -f /project/user-app/preload-m2-pom.xml liberty:install-server dependency:go-offline && \
    rm /project/user-app/preload-m2-pom.xml

# Copy and run a simple version check
COPY --chown=java_user:java_group ./util /project/util
RUN     /project/util/check_version build

# Copy the validate.sh script and application pom.xml
COPY --chown=java_user:java_group ./validate.sh /project/user-app/validate.sh
# -- This is the first app-specific piece --
# AJM COPY --chown=java_user:java_group ./user-app/pom.xml /project/user-app/pom.xml
# Validate 
# AJM RUN cd /project/user-app && ./validate.sh build

# Copy the rest of the application source
# AJM COPY --chown=java_user:java_group ./user-app /project/user-app

# Build (and run unit tests) 
#  also liberty:create copies config from src->target
#  also remove quick-start-security.xml since it's convenient for local dev mode but should not be in the production image.
# AJM RUN cd /project/user-app && \
#    rm -f src/main/liberty/config/configDropins/defaults/quick-start-security.xml && \
#    mvn -Pappsody-build -B liberty:create package

# process any resources or shared libraries - if they are present in the dependencies block for this project (there may be none potentially)
# test to see if each is present and move to a well known location for later processing in the next stage
# 
#RUN cd /project/user-app/target/liberty/wlp/usr/servers && \
#    if [ -d ./defaultServer/lib ]; then mv ./defaultServer/lib /data/configlibdir; fi && \
#    if [ ! -d /configlibdir/lib ]; then mkdir /data/configlibdir/lib; fi && \
#    mv -f defaultServer/* /data/config/ && \
#    if [ -d ../shared ]; then mv ../shared/* /data/shared/; fi

USER root

RUN mkdir -m 777 -p /artifacts
RUN mkdir -m 777 -p /projects

RUN mkdir -m 777 -p /data/config/resources

COPY --chown=1001:0 bin/. /artifacts/bin
#RUN chmod -R 777 /home/java_user/.m2/repository
#COPY --chown=1001:0 /home/java_user/.m2/repository /home/user/.m2/repository